INSERT INTO MTS_APP_SETTINGS VALUES('CALCULATE_WEEK_END_DATE','RETAILER_SERVICES','false','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('ALT_ID_FLAG','RETAILER_SERVICES','false','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('AUTH_CONNECT_TIMEOUT','RETAILER_SERVICES','1000','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('AUTH_READ_TIMEOUT','RETAILER_SERVICES','4000','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('AUTH_SUCCEGL_MEGLAGE','RETAILER_SERVICES','','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('AUTH_FAIL_MEGLAGE','RETAILER_SERVICES','Unable to authenticate credential.','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('AUTH_SERVICE_LOCATION','RETAILER_SERVICES','http://www2cert.meijer.com/mperkGLhopperManager/ShopperManager.svc?wsdl','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('CLIPPED_OFFERS_CONNECT_TIMEOUT','RETAILER_SERVICES','1000','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('CLIPPED_OFFERS_READ_TIMEOUT','RETAILER_SERVICES','15000','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('CLIPPED_OFFERS_PAGE_SIZE','RETAILER_SERVICES','99','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('CLIPPED_OFFERS_PAGE_NUMBER','RETAILER_SERVICES','1','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('CLIPPED_OFFERS_SERVICE_LOCATION','RETAILER_SERVICES','http://www2cert.meijer.com/mperkGLhopperQuery/ShopperQuery.svc?wsdl','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('USERNAME','RETAILER_SERVICES','Modiv','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('PAGLWORD','RETAILER_SERVICES','CXs37R*jKPla','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('FILTER_INCLUDE_FLAG','GEO_TARGETING','true','GL');
INSERT INTO MTS_APP_SETTINGS VALUES('OPCO_SALEWEEK_CONFIG','RETAILER_SERVICES','5','GL');

