CALCULATE_WEEK_END_DATE,RETAILER_SERVICES,false,AUSA
WALLET_DURATION_RULES,MEDIA_DELIVERY,"""CATALINA_MAN:RTO",AUSA
MORPHEUS_ENABLED_FLAG,MORPHEUS_SERVICES,true,AUSA
MTS_LANDING_URL,SOCIAL_OPT_IN,http://ausa.mts.qa.modivmedia.net/mts/view/fb/landing,AUSA
GLOBAL_FLAG,SOCIAL_OPT_IN,false,AUSA
SECONDARY_IMP_CAP,MEDIA_DELIVERY,2,AUSA

RETAILER_NAME,MORPHEUS_SERVICES,AUSA,AUSA
ALT_ID_FLAG,RETAILER_SERVICES,false,AUSA

MAX_NO_OFFER_INTERVAL_IN_SEC,MEDIA_DELIVERY,180,AUSA
UPDATE_RTO_INTERVAL_IN_MIN,MEDIA_DELIVERY,10,AUSA
SECONDARY_IMP_WAIT_INTERVAL_IN_SEC,MEDIA_DELIVERY,180,AUSA
ALLOW_BLOCKBUSTER_OFFERS,MEDIA_DELIVERY,false,AUSA
BACKFILL_RULES,MEDIA_DELIVERY,EYC_MAN:4;CATALINA_MAN:4;AHOLD_MAN:0;EYC_RET:0;CATALINA_RET:0;AHOLD_RET:0,AUSA
OFFER_VARIETY_RULES,MEDIA_DELIVERY,AHOLD_RET;,AUSA
AUTH_CONNECT_TIMEOUT,RETAILER_SERVICES,1000,AUSA
AUTH_READ_TIMEOUT,RETAILER_SERVICES,4000,AUSA
AUTH_SUCCESS_MESSAGE,RETAILER_SERVICES,,AUSA
AUTH_FAIL_MESSAGE,RETAILER_SERVICES,Unable to authenticate credential.,AUSA
AUTH_SERVICE_LOCATION,RETAILER_SERVICES,http://www2cert.meijer.com/mperksShopperManager/ShopperManager.svc?wsdl,AUSA
CLIPPED_OFFERS_CONNECT_TIMEOUT,RETAILER_SERVICES,1000,AUSA
CLIPPED_OFFERS_READ_TIMEOUT,RETAILER_SERVICES,15000,AUSA
CLIPPED_OFFERS_PAGE_SIZE,RETAILER_SERVICES,99,AUSA
CLIPPED_OFFERS_PAGE_NUMBER,RETAILER_SERVICES,1,AUSA
CLIPPED_OFFERS_SERVICE_LOCATION,RETAILER_SERVICES,http://www2cert.meijer.com/mperksShopperQuery/ShopperQuery.svc?wsdl,AUSA
USERNAME,RETAILER_SERVICES,Modiv,AUSA
PASSWORD,RETAILER_SERVICES,CXs37R*jKPla,AUSA
FB_SCOPE,SOCIAL_OPT_IN,"""publish_stream",AUSA
CLIENT_ID,SOCIAL_OPT_IN,236567309732138,AUSA
CLIENT_SECRET,SOCIAL_OPT_IN,ba7a45d201402301348292e95ec880cb,AUSA


STATIC_NOTIFICATION_FLAG,GEO_TARGETING,true,AUSA
DYNAMIC_NOTIFICATION_FLAG,GEO_TARGETING,true,AUSA
NOTIFICATION_MESSAGES,GEO_TARGETING,geo.sta.ent.def:Use ScanIt to save time and jump the line||geo.dyn.ent.def:You have ${num_offers} offers saving you $${savings} ready to use today.,AUSA
FILTER_INCLUDE_FLAG,GEO_TARGETING,true,AUSA
NOTIFICATION_LIMIT_TIMEOUT,GEO_TARGETING,1,AUSA
NOTIFICATION_FILTER_STORES,GEO_TARGETING,17:18:19:20:21,AUSA
NOTIFICATION_FILTER_RETAILERS,GEO_TARGETING,AUSA,AUSA
NOTIFICATION_FILTER_OPCOS,GEO_TARGETING,SS,AUSA
MAX_NOTIFICATION_LIMIT,GEO_TARGETING,100,AUSA


OPCO_SALEWEEK_CONFIG,RETAILER_SERVICES,7,AUSA
